# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Androcode
tagline:          'Desarrollo Android en español y tal'
description:      'Androcode es programación, Androcode es tecnología, Androcode necesita una descripción nueva.'
url:              http://androcode.es
baseurl:          /

paginate:         5
